apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: airflow-scheduler
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "delete", "get", "watch", "list"]
