apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
spec:
  selector:
    matchLabels:
      app: airflow-webserver
  template:
    metadata:
      labels:
        app: airflow-webserver
    spec:
      initContainers:
        - name: db-init
          image: houstonj1/airflow:latest
          imagePullPolicy: Always
          command:
            - "/bin/sh"
            - "-c"
          args:
            - "airflow initdb && airflow upgradedb"
          envFrom:
            - configMapRef:
                name: airflow-config
      containers:
        - name: webserver
          image: houstonj1/airflow:latest
          imagePullPolicy: Always
          command:
            - "airflow"
            - "webserver"
          envFrom:
            - configMapRef:
                name: airflow-config
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 50
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 50
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 1
