apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
data:
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql://airflow:airflow@postgres-postgresql.default.svc.cluster.local/airflow"
  AIRFLOW__CORE__LOAD_EXAMPLES: "false"
